### ISSUE TITLE
Table name should be configurable

### ISSUE THREAD

**Issue by theborakompanioni** [audit4j/audit4j-db#2]
The automatic creation of a table named "audit" prevents me from using this library in a project.

Is there something that prevents the table name from being configurable? Is there any chance this will be implemented? Do you accept pull-requests?

**Comment by janithb** [comment]
Nothing is preventing this being configurable. We will be able to add this change to next audit4j-db version (2.4.2, probably 2.4.1 ).

We do accept pull requests.
